providers:
  openai:
    clients:
      sync: OpenAI
      async: AsyncOpenAI
    imports:
      clients: from openai import OpenAI, AsyncOpenAI
    model_types:
      llm:
        message_converter: convert_to_openai_message
        message_converter_type: ChatCompletionMessageParam
        imports:
          converter: from astral_ai.messaging.providers.openai import convert_to_openai_message
          types: from openai.types.chat.chat_completion_message_param import ChatCompletionMessageParam as OpenAIMessage

  azureOpenAI:
    clients:
      sync: AzureOpenAI  
      async: AsyncAzureOpenAI
    imports:
      clients: from openai import AzureOpenAI, AsyncAzureOpenAI
    model_types:
      llm:
        message_converter: convert_to_openai_message
        message_converter_type: ChatCompletionMessageParam
        imports:
          converter: from astral_ai.messaging.providers.openai import convert_to_openai_message
          types: from openai.types.chat.chat_completion_message_param import ChatCompletionMessageParam as OpenAIMessage

  anthropic:
    clients:
      sync: Anthropic
      async: AsyncAnthropic
    imports:
      clients: from anthropic import Anthropic, AsyncAnthropic
    model_types:
      llm:
        message_converter: convert_to_anthropic_message
        message_converter_type: ChatCompletionMessageParam
        imports:
          converter: from astral_ai.messaging.providers.anthropic import convert_to_anthropic_message
          types: from anthropic.types.chat.chat_completion_message_param import ChatCompletionMessageParam as AnthropicMessage
